# Generated by Django 5.1 on 2025-09-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0001_initial"),
    ]

    operations = []
