# Generated by Django 5.1 on 2025-06-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0019_dadoscampo_tipo_esporte"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadoscampo",
            name="coordenada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login_app.coordenada",
            ),
        ),
    ]
