# Generated by Django 5.1 on 2025-06-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_app", "0020_dadoscampo_coordenada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dadoscampo",
            name="coordenada",
        ),
    ]
